name: 'ansible GitHub Actions'

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["TF GitHub Actions"]
    types:
      - completed
jobs:
ansible:
  runs-on: ubuntu-latest
  steps:
    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: ./playbook_ansible_autoscaling.yml # path to your Ansible playbook
        directory: ./
        key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
        inventory: ./hosts # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets
